In [1]:
import numpy as np

In [2]:
my_list = [1, 2 ,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
#10 points linearly spaced from 0 to 11, evenly spaced
np.linspace(0, 11, 10)

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [19]:
#random integers
np.random.randint(0, 1000)

744

In [23]:
#random integers in a 3X3 dimension
np.random.randint(0, 1000, (3, 3))

array([[469, 797, 835],
       [525, 548,  39],
       [ 53, 146, 181]])

In [24]:
#draw random samples from a normal (Gaussian) distribution
#np.random.normal

In [25]:
#np random seed
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [27]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [28]:
arr.max()

95

In [29]:
arr.min()

9

In [30]:
arr.mean()

60.799999999999997

In [31]:
arr.argmax()

0

In [32]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [33]:
arr.reshape(2, 5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [35]:
mat = np.arange(0, 100).reshape(10, 10)

In [36]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
mat[0, 1]

1

In [38]:
mat[4, 3]

43

In [43]:
#first row
mat[0, :]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#second column
mat[:, 1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
#select first 3 by 3 matrix
mat[:3, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [48]:
#boolean masking
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])